# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
description: >-
  Overlay Improvement Proposals (OIPs) describe standards for the Overlay
  platform, including core protocol specifications, client APIs, and contract
  standards.
url: "https://oips.overlay.market"
repository: overlay-market/OIPs
twitter_username: OverlayProtocol
github_username: overlay-market
header_pages:
  - all-OIP.html
twitter:
  card: summary
  username: OverlayProtocol

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-seo-tag

permalink: /:slug

defaults:
  - scope:
      path: "OIPs"
    values:
      layout: "OIP"

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - OIP-X.md
